### PR TITLE
feat: allow a manager that performs no actions

### PR DESCRIPTION
**Pull request by SMillerDev**
And make sure the two keep in sync by using an interface.

### CODE REVIEW

**Comment by pprkut** [comment]
I don't think we need the Interface. I don't see a use for this anywhere outside tests. So let's just make it a test helper and have it extend the main one

**Comment by SMillerDev** [comment]
So something like `Resque\Tests\MockManagerHelper`? Or would you prefer to have it in our stack?

**Comment by pprkut** [comment]
No, here is fine. We can reevaluate once we actually try to upstream it. I'd put it in a subdirectory though, so `test/Resque/Helpers` perhaps, or `test/Resque/Mocks`

**Comment by SMillerDev** [comment]
Merged in https://github.com/pprkut/php-resque/commit/7b0537bd2461186e9ae1aff9f424e374477f7a7a

**Pull request closed without merging**
